[package]
name = "maid"
version = "0.1.0"
authors = ["Luke Wilson"]

[dependencies]
# Argument parsing
structopt = "0.1.6"
structopt-derive = "0.1.6"
# TOML
serde = "1.0.24"
serde_derive = "1.0.24"
toml = "0.4.5"
