[package]
name = "maid"
version = "1.0.0"
authors = ["Luke Wilson"]

[dependencies]
ansi_term = "0.10.2"
# Argument parsing
structopt = "0.1.6"
structopt-derive = "0.1.6"
# TOML
serde = "1.0.24"
serde_derive = "1.0.24"
toml = "0.4"
